#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Windows + Docker Desktop GPU passthrough onboarding.
# ──────────────────────────────────────────────────────────────────────────

# Persist detected values next to this script, not the repo-root .env, so
# this wizard's state never collides with other .env files in the repo.
# Assumes the documented invocation: run from the repo root as
# `bash apps/host/plaiground_host/workspace/wizard_windows_gpu_setup.sh`.
ENV_FILE="${ENV_FILE:-apps/host/plaiground_host/workspace/.env}"

TOTAL_STAGES=4

banner "plaiground: Windows GPU + Docker onboarding"

# ── Stage 1: WSL2 ───────────────────────────────────────────────────────────
stage "WSL2 확인"
say "Docker Desktop이 로컬 GPU를 컨테이너에 전달하려면 WSL2 플랫폼만 켜져 있으면 됩니다."
note "Ubuntu 같은 배포판은 필요 없습니다 — Docker Desktop이 자체 내부 배포판을 알아서 만듭니다."
note "일부 구형 wsl.exe는 --status/--version에서 '기본 배포판 없음' 에러를 내는 버그가 있어, 자동 감지 대신 직접 확인해 주세요."

step "관리자 권한으로 PowerShell을 열고 순서대로 실행하세요:"
step "  wsl --update"
step "  wsl --set-default-version 2"
step "  wsl --status"
note "마지막 명령에서 '배포판이 없다'는 안내만 뜨고 WSL_E_DEFAULT_DISTRO_NOT_FOUND 같은 에러 코드가 없으면 정상입니다."
pause "위 세 명령을 실행하고 결과를 확인했으면 Enter"

if confirm "wsl --status가 에러 코드 없이 버전 정보를 보여줬나요?"; then
  write_env WSL2_READY "true"
else
  warn "아직 안 됐다면 컴퓨터를 재부팅한 뒤 위 세 명령을 다시 실행해 보세요."
  SKIPPED+=("WSL2 확인 — wsl --status 에러 지속")
  write_env WSL2_READY "manual"
fi

# ── Stage 2: NVIDIA 드라이버 ─────────────────────────────────────────────────
stage "NVIDIA 드라이버 확인"
say "드라이버가 최신이어야 컨테이너 안에서도 GPU가 보입니다."

if driver_info=$(nvidia-smi.exe --query-gpu=name,driver_version --format=csv,noheader 2>/dev/null); then
  gpu_name=$(printf '%s' "$driver_info" | cut -d',' -f1 | xargs)
  driver_version=$(printf '%s' "$driver_info" | cut -d',' -f2 | xargs)
  note "감지됨: $gpu_name / 드라이버 $driver_version"
  write_env DETECTED_GPU_NAME "$gpu_name"
  write_env DETECTED_DRIVER_VERSION "$driver_version"
else
  warn "nvidia-smi를 찾을 수 없습니다 — 드라이버가 없거나 오래되었을 수 있습니다."
  open_url "https://www.nvidia.com/en-us/drivers/"
  step "본인 GPU에 맞는 최신 드라이버를 검색해 다운로드, 설치하세요."
  pause "설치 완료 후 Enter"
  if driver_info=$(nvidia-smi.exe --query-gpu=name,driver_version --format=csv,noheader 2>/dev/null); then
    gpu_name=$(printf '%s' "$driver_info" | cut -d',' -f1 | xargs)
    driver_version=$(printf '%s' "$driver_info" | cut -d',' -f2 | xargs)
    note "감지됨: $gpu_name / 드라이버 $driver_version"
    write_env DETECTED_GPU_NAME "$gpu_name"
    write_env DETECTED_DRIVER_VERSION "$driver_version"
  else
    warn "여전히 감지 안 됨. 이 단계는 나중에 다시 시도하세요 (스크립트를 재실행하면 여기부터 다시 확인합니다)."
    SKIPPED+=("NVIDIA 드라이버 확인 — nvidia-smi 미탐지")
  fi
fi

# ── Stage 3: Docker Desktop + WSL2 백엔드 ───────────────────────────────────
stage "Docker Desktop 설치 확인"
say "Docker Desktop이 WSL2 엔진을 쓰면 별도 설정 없이 GPU 컨테이너가 됩니다."

if docker_version=$(docker.exe --version 2>/dev/null); then
  note "감지됨: $docker_version"
else
  warn "Docker를 찾을 수 없습니다."
  open_url "https://www.docker.com/products/docker-desktop/"
  step "Docker Desktop을 다운로드해 설치하세요 (설치 중 'Use WSL 2 instead of Hyper-V' 옵션은 기본 체크 상태로 두세요)."
  step "설치 후 Docker Desktop을 실행하고, Settings → Resources → WSL Integration에서 사용 중인 배포판 토글을 켜세요."
  pause "설치 및 설정을 마쳤으면 Enter"
fi

# ── Stage 4: GPU 패스스루 최종 검증 ─────────────────────────────────────────
stage "GPU 패스스루 최종 검증"
say "테스트 컨테이너를 실제로 띄워서 GPU가 보이는지 확인합니다 (최초 1회는 이미지 다운로드로 몇 분 걸릴 수 있습니다)."

if confirm "지금 검증 컨테이너를 실행할까요?"; then
  if docker.exe run --rm --gpus all nvidia/cuda:12.1.1-base-ubuntu22.04 nvidia-smi; then
    if confirm "위 출력에 GPU 이름이 정상적으로 보이나요?"; then
      write_env WINDOWS_GPU_READY "true"
      note "GPU 패스스루 준비 완료. plaiground-base 이미지를 --gpus all 로 실행할 수 있습니다."
    else
      SKIPPED+=("GPU 패스스루 검증 — 사용자가 출력 확인 실패로 표시")
      warn "Docker Desktop을 재시작하거나 컴퓨터를 재부팅한 뒤 이 스크립트를 다시 실행해 보세요."
    fi
  else
    SKIPPED+=("GPU 패스스루 검증 — 컨테이너 실행 자체가 실패")
    warn "컨테이너 실행이 실패했습니다. Stage 1~3을 다시 확인하거나 재부팅 후 재시도하세요."
  fi
else
  SKIPPED+=("GPU 패스스루 검증 — 건너뜀")
fi

finish
